import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <nav>
          <ul>
            <li>
              <Link href="/about">Custom Express route</Link>
            </li>
            <li>
              <Link href="/posts">SSG/ISR</Link>
            </li>
            <li>
              <Link href="/users">SSR</Link>
            </li>
            <li>
              <Link href="/comments">CSR</Link>
            </li>
            <li>
              <Link href="/product">useQuery</Link>
            </li>
            <li>
              <Link href="/api/graphql">Apollo Graphql service</Link>
            </li>
          </ul>
        </nav>
      </main>
    </>
  );
}
